urls.py
from django.urls import path
from . import views

app_name = 'geriatrics'

urlpatterns = [
    path('', views.Admissions.as_view(template_name='geriatrics/admissions/admission_list.html'), name='admissions'),
    path('<int:pk>/', views.AdmissionDetailView.as_view(template_name='geriatrics/admissions/admission_detail.html'), name='admission-detail'),
]

models.py
from django.db import models
from django.urls import reverse
from django.utils.timesince import timesince
from birthday.fields import BirthdayField
from birthday.managers import BirthdayManager
from django.conf import settings

SEX = (
    ('male', 'Male'),
    ('female', 'Female'),
    )

CIVIL_STATUS = (
    ('single', 'Single'),
    ('married', 'Married'),
    ('widowed', 'Widowed'),
    )

LEVEL_OF_CARE = (
    ('high', 'High'),
    ('intermediate', 'Intermediate'),
    ('low', 'Low'),
    )

#Geriatric Models   
class Residence(models.Model):
    name = models.CharField(max_length=70)
    address = models.TextField(max_length=175, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'{self.name}'

class Admission(models.Model):
    date_of_admission = models.DateField(auto_now=False, null=False, blank=False)
    time_of_admission = models.TimeField(auto_now=False, null=False, blank=False)
    admitting_diagnosis = models.TextField(blank=True)
    admitted_at = models.ForeignKey('Residence', on_delete=models.PROTECT, null=True)
    resident = models.OneToOneField('Resident', on_delete=models.CASCADE)
    level_of_care = models.CharField(max_length=12, choices=LEVEL_OF_CARE, blank=True)    
    discharged = models.BooleanField(default=False, editable=False)
    admitted_by = models.CharField(max_length=120, blank=True)
    relatives = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    class Meta:
        ordering = ['date_of_admission']

    def __str__(self):
        return f'{self.resident}'

    def get_absolute_url(self):
        return reverse('geriatrics:admission-detail', args=[str(self.id)])

class Discharge(models.Model):
    admission = models.OneToOneField('Admission', on_delete=models.CASCADE)
    date_of_discharge = models.DateField(auto_now=False)
    reason = models.TextField(max_length=175)
    deceased = models.BooleanField(default=False)
    date_of_death = models.DateField(auto_now=False, null=True, blank=True, verbose_name='died_on')
    time_of_death = models.TimeField(auto_now=False, null=True, blank=True)
    cause_of_death = models.TextField(max_length=175, blank=True)

    class Meta:
        ordering = ['date_of_discharge']

    def __str__(self):
        return f'{self.admission.resident} - Discharged: {self.date_of_discharge}'

class Resident(models.Model):
    last_name = models.CharField(max_length=35)
    given_name = models.CharField(max_length=35, verbose_name='name')
    middle_name = models.CharField(max_length=35, blank=True)
    photo = models.ImageField(
            null=True,
            blank=True,
            upload_to="photos/residents/%Y/%m/%D",
            )
    sex = models.CharField(max_length=6, choices=SEX, blank=False)
    osca_id = models.CharField(max_length=24, blank=True)
    philhealth_number = models.CharField(max_length=24, blank=True)
    address = models.TextField(max_length=175)
    #date_of_birth = models.DateField(auto_now=False)
    date_of_birth = BirthdayField()
    objects = BirthdayManager()
    birth_place = models.CharField(max_length=35, blank=True)
    nationality = models.CharField(max_length=70, blank=True)
    civil_status = models.CharField(max_length=7, choices=CIVIL_STATUS, blank=True)
    most_recent_occupation = models.CharField(max_length=70, blank=True)
    religion = models.CharField(max_length=70, blank=True)
    reminders = models.CharField(max_length=180, blank=True)
    diet = models.TextField(blank=True)
    weight_in_kg = models.FloatField(null=True, blank=True)
    height_in_cm = models.FloatField(null=True, blank=True)   

    class Meta:
        ordering = ['last_name', 'given_name']

    def __str__(self):
        return f'{self.last_name}, {self.given_name}' 

views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import Residence, Admission
from .tables import AdmissionsTable
from patient_monitoring.tables import VitalSignsTable, FluidIntakeAndOutputTable, TurningScheduleTable
from patient_monitoring.models import VitalSigns, FluidIntakeAndOutput, TurningSchedule
from plan_of_care.tables import PlanOfCareTable
from plan_of_care.models import PlanOfCare
from medication.tables import MedicationTable
from medication.models import Medication
from kardex.models import OrganSystem
from django_tables2 import MultiTableMixin
from django.http import HttpResponseForbidden

# Create your views here.
"""def admissions(request, residence_id=None):
    residence = None
    residences = Residence.objects.all()
    admissions = Admission.objects.filter(discharged=False)
    if residence_id:
        residence = get_object_or_404(Residence, id=residence_id)
        admissions = admissions.filter(residence=residence)
    return render(request, 'geriatrics/admissions/list.html', {'residence': residence, 'residences': residences, 'admissions': admissions})"""

class Admissions(LoginRequiredMixin, generic.ListView):
    model = Admission

    def get_context_data(self, **kwargs):
        context = super(Admissions, self).get_context_data(**kwargs)
        context['title'] = 'Admissions'
        table = AdmissionsTable(Admission.objects.filter(discharged=False))
        table.paginate(page=self.request.GET.get("page", 1), per_page=5)
        context['table'] = table
        return context

class AdmissionDetailView(UserPassesTestMixin, MultiTableMixin, generic.DetailView):
    model = Admission
    tables = []
    table_pagination = {
        "per_page": 10 
    }

    def handle_no_permission(self):
        return HttpResponseForbidden()

    def test_func(self):
        #print(self.request.build_absolute_uri(self.request.get_full_path()))
        obj = super().get_object()
        return self.request.user in obj.relatives.all() or self.request.user.is_staff

    def get_object(self):
        obj = super().get_object()
        resident=obj.id
        vs_table = VitalSignsTable(
                VitalSigns.objects.filter(
                    resident=resident
                    )
                )
        io_table = FluidIntakeAndOutputTable(
                FluidIntakeAndOutput.objects.filter(
                    resident=resident
                    )
                )
        turn_table = TurningScheduleTable(
                TurningSchedule.objects.filter(
                    resident=resident
                    )
                )
        planofcare_table = PlanOfCareTable(
                PlanOfCare.objects.filter(
                    resident=resident
                    )
                )
        medication_table = MedicationTable(
                Medication.objects.filter(
                    resident=resident
                    )
                )
        self.tables.append(vs_table)
        self.tables.append(io_table)
        self.tables.append(turn_table)
        self.tables.append(planofcare_table)
        self.tables.append(medication_table)
        return obj

    def get_context_data(self, **kwargs):
        context = super(AdmissionDetailView, self).get_context_data(**kwargs)
        context['title'] = 'Admission Detail'
        #context['systems'] = OrganSystem.objects.all()
        return context

templates/geriatrics/admissions/admission_detail.html
{% extends 'geriatrics/base.html' %}
{% load static %}

{% block title %}
  Geriatrics | {{ title }}
{% endblock %}

{% block header %}
  {% include 'geriatrics/includes/header.html' %}
{% endblock %}

{% block content %}  
<div class="row p-2">  
  <div id="main" class="col-md-9">
    {% if perms.geriatrics.view_admission %}
    <h3>{{ admission.resident }}</h3>
    <div class="row">
      {% with resident=admission.resident %}
      <div class="col-md-3">
      {% if resident.photo %}
          <div class="text-center"><img src="{{ resident.photo.url }}" class="img-thumbnail" alt="Responsive image" width="300" height="199"></div>
        {% else %}
          <div class="text-center"><img src="{% static "img/avatar.png" %}" class="img-thumbnail" alt="Avatar"></div>
        {% endif %}
        
    <!-- Tab navs -->
    <div
      class="nav flex-column nav-tabs text-center"
      id="v-tabs-tab"
      role="tablist"
      aria-orientation="vertical"
    >
      <a
        class="nav-link"
        id="v-tabs-profile-tab"
        data-mdb-toggle="tab"
        href="#v-tabs-profile"
        role="tab"
        aria-controls="v-tabs-profile"
        aria-selected="false"
        >Resident Profile</a
      >
      <a
        class="nav-link"
        id="v-tabs-overview-tab"
        data-mdb-toggle="tab"
        href="#v-tabs-overview"
        role="tab"
        aria-controls="v-tabs-overview"
        aria-selected="false"
        >Systematic Overview</a
      >
      <a
        class="nav-link"
        id="v-tabs-kardex-tab"
        data-mdb-toggle="tab"
        href="#v-tabs-kardex"
        role="tab"
        aria-controls="v-tabs-kardex"
        aria-selected="false"
        >Kardex</a
      >
      <a
        class="nav-link"
        id="v-tabs-documents-tab"
        data-mdb-toggle="tab"
        href="#v-tabs-documents"
        role="tab"
        aria-controls="v-tabs-documents"
        aria-selected="false"
        >Scanned Documents</a
      >
      <a
        class="nav-link"
        id="v-tabs-vs-tab"
        data-mdb-toggle="tab"
        href="#v-tabs-vs"
        role="tab"
        aria-controls="v-tabs-vs"
        aria-selected="false"
        >Patient Monitoring</a
      >
    </div>
    <!-- Tab navs -->
  </div>

  <div class="col-md-9">
    <!-- Tab content -->
    <div class="tab-content" id="v-tabs-tabContent">
      <div
        class="tab-pane fade"
        id="v-tabs-profile"
        role="tabpanel"
        aria-labelledby="v-tabs-profile-tab"
      >
        {% include 'geriatrics/includes/resident_profile.html' %}
      </div>
      <div
        class="tab-pane fade"
        id="v-tabs-overview"
        role="tabpanel"
        aria-labelledby="v-tabs-overview-tab"
      >
        {% include 'kardex/systematic_overview_tablist.html' %}
      </div>
      <div
        class="tab-pane fade"
        id="v-tabs-kardex"
        role="tabpanel"
        aria-labelledby="v-tabs-kardex-tab"
      >
        {% include 'kardex/kardex_tablist.html' %}
      </div>      
      <div
        class="tab-pane fade"
        id="v-tabs-documents"
        role="tabpanel"
        aria-labelledby="v-tabs-documents-tab"
      >
        {% include 'scanned_docs/scanned_docs.html' %}
      </div>
      <div
        class="tab-pane fade"
        id="v-tabs-vs"
        role="tabpanel"
        aria-labelledby="v-tabs-vs-tab"
      >
        {% include 'patient_monitoring/patient_monitoring_tablist.html' %}       
      </div>
    </div>
    <!-- Tab content -->
  </div>
      
      {% endwith %}
    </div>
    {% else %}
      <div class="alert alert-dismissible alert-warning fade show">
        <button type="button" class="close" data-mdb-dismiss="alert">&times;</button>
        <h4 class="alert-heading">Oh snap!</h4>
        <p class="mb-0">You don't have permission to access the contents of this page. Please <a href="{% url 'cm_portal:contact' %}" class="alert-link">contact</a> your web administrator to request access.</p>
      </div>
    {% endif %}
    
  </div>
  {% include 'geriatrics/includes/sidebar.html' %}
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'scripts/admission_detail.js' %}"></script>
{% endblock %}

templates/geriatrics/admissions/admission_list.html
{% extends 'geriatrics/base.html' %}
{% load static %}

{% block title %}
  Geriatrics | {{ title }}
{% endblock %}

{% block header %}
  {% include 'geriatrics/includes/header.html' %}
{% endblock %}

{% block content %}
<div class="row p-2">      
  <div id="main" class="col-lg-9">
    <h3>All admissions</h3>
    {% if perms.geriatrics.view_admission %}
    <div class="row">
      {% if admission_list %}
        {% load render_table from django_tables2 %}
        {% render_table table %}
      {% else %}
        <div class="alert alert-dismissible alert-info fade show">
          <button type="button" class="close" data-mdb-dismiss="alert">&times;</button>
          <h4 class="alert-heading">Heads up!</h4>
          <p class="mb-0">There is nothing to show; database is currently empty. Please <a href="{% url 'geriatrics_admin:index' %}" class="alert-link">create</a> a record first.</p>
        </div>     
      {% endif %}
    </div>
    {% else %}
      <div class="alert alert-dismissible alert-warning fade show">
        <button type="button" class="close" data-mdb-dismiss="alert">&times;</button>
        <h4 class="alert-heading">Oh snap!</h4>
        <p class="mb-0">You don't have permission to access the contents of this page. Please <a href="{% url 'cm_portal:contact' %}" class="alert-link">contact</a> your web administrator to request access.</p>
      </div>
    {% endif %}
  </div>
  {% include 'geriatrics/includes/sidebar.html' %}
</div>
{% endblock %}

templates/geriatrics/base.html
{% extends 'cm_portal/base.html' %}

templates/geriatrics/includes/header.html
<header>
  {% include 'core/includes/navbar.html' %}
  <div class="card card-intro sky-gradient">
    <div class="card-body white-text rgba-black-light text-center">
      <!--Grid row-->
      <div class="row d-flex justify-content-center">
        <!--Grid column-->
        <div class="col-md-6">
          <h1 class="font-weight-bold h2">{{ title }}</h1>
        </div>
      <!--Grid column-->
      </div>
    <!--Grid row-->
    </div>
  </div>
</header>

templates/geriatrics/includes/residences.html
<h3>Residences</h3>
<ul class="nav nav-pills flex-column">
  <li class="nav-item">
    <a {% if not residence %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="{% url 'geriatrics:admissions' %}" >Admissions</a>
  </li>
  {% for r in residences %}
    <li class="nav-item">
      <a {% if residence.id == r.id %}class="nav-link active"{% else %}class="nav-link"{% endif %} href="#" >{{ r.name|capfirst }}</a>
    </li>
  {% endfor %}    
</ul>
<hr>

templates/geriatrics/includes/resident_profile.html
<h4 class="text-center">Resident Profile</h4>
<div class="table-responsive-sm">
  <table class="table table-sm table-hover">
    <tr>
      <td colspan="3"><strong>Reminder(s): </strong>{{ resident.reminders }}</td>          
    </tr>
    <tr>
      <td rowspan="2"><strong>Diagnosis: </strong>{{ admission.admitting_diagnosis }}</td>
      <td rowspan="2"><strong>Diet: </strong>{{ resident.diet }}</td>
      <td><strong>Weight: </strong>{{ resident.weight }}</td>
    </tr>     
    <tr>      
      <td><strong>Height: </strong>{{ resident.height }}</td>
    </tr>
    <tr>
      <td><strong>Surname: </strong>{{ resident.last_name }}</td>
      <td><strong>First Name: </strong>{{ resident.given_name }}</td>
      <td><strong>Middle Name: </strong>{{ resident.middle_name }}</td>    
    </tr>
    <tr>
      <td>
        <strong>Age: </strong>
        {% if admission.discharged %}
          <strong>Resident has been discharged</strong>        
        {% else %}
          {{ resident.date_of_birth|timesince }} old
        {% endif %}
      </td>
      <td><strong>Birth Date: </strong>{{ resident.date_of_birth }}</td>
      <td><strong>OSCA ID #: </strong>{{ resident.osca_id }}</td>    
    </tr>
    <tr>
      <td colspan="2"><strong>Address: </strong>{{ resident.address }}</td>
      <td><strong>Philhealth #: </strong>{{ resident.philhealth_number }}</td>     
    </tr>
    <tr>       
        
      <td colspan="2"><strong>Most Recent Occupation: </strong>{{ resident.most_recent_occupation }}</td>
      <td><strong>Maxicare #: </strong>{{ resident.maxicare_number }}</td>          
    </tr>
    <tr>     
      <td><strong>Date of Admission: </strong>{{ admission.date_of_admission }}</td>
      <td><strong>Time of Admission: </strong>{{ admission.time_of_admission }}</td> 
      <td><strong>Room: </strong>{{ resident.room }}</td>   
    </tr>
  </table> 
</div>
  
 

templates/geriatrics/includes/sidebar.html
<div id="sidebar" class="col-md-3 p-2">  
  {% include 'cm_portal/includes/our_services.html' %}
  {% include 'geriatrics/includes/residences.html' %}
</div>